// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RankenClassSchedule.Models.DataLayer;

#nullable disable

namespace RankenClassSchedule.Migrations
{
    [DbContext(typeof(ClassScheduleContext))]
    [Migration("20250416143940_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<string>("MilitaryTime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClassId");

                    b.HasIndex("DayId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            DayId = 1,
                            MilitaryTime = "0800",
                            Number = 100,
                            TeacherId = 1,
                            Title = "Intro to C#"
                        },
                        new
                        {
                            ClassId = 2,
                            DayId = 2,
                            MilitaryTime = "1000",
                            Number = 101,
                            TeacherId = 1,
                            Title = "Intro to Web Dev"
                        },
                        new
                        {
                            ClassId = 3,
                            DayId = 1,
                            MilitaryTime = "1000",
                            Number = 200,
                            TeacherId = 1,
                            Title = "Intro to Python"
                        },
                        new
                        {
                            ClassId = 4,
                            DayId = 1,
                            MilitaryTime = "0800",
                            Number = 300,
                            TeacherId = 3,
                            Title = "JavaScript Intermediat"
                        },
                        new
                        {
                            ClassId = 5,
                            DayId = 1,
                            MilitaryTime = "1000",
                            Number = 300,
                            TeacherId = 3,
                            Title = "JavaScript Advanced"
                        },
                        new
                        {
                            ClassId = 6,
                            DayId = 4,
                            MilitaryTime = "1200",
                            Number = 400,
                            TeacherId = 1,
                            Title = "Django Framework"
                        },
                        new
                        {
                            ClassId = 7,
                            DayId = 4,
                            MilitaryTime = "1400",
                            Number = 501,
                            TeacherId = 4,
                            Title = "Learn Database"
                        },
                        new
                        {
                            ClassId = 8,
                            DayId = 4,
                            MilitaryTime = "1400",
                            Number = 502,
                            TeacherId = 1,
                            Title = "Python Advanced"
                        },
                        new
                        {
                            ClassId = 9,
                            DayId = 1,
                            MilitaryTime = "1200",
                            Number = 402,
                            TeacherId = 2,
                            Title = "HTML CSS"
                        },
                        new
                        {
                            ClassId = 10,
                            DayId = 3,
                            MilitaryTime = "1400",
                            Number = 502,
                            TeacherId = 2,
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            ClassId = 11,
                            DayId = 5,
                            MilitaryTime = "1600",
                            Number = 202,
                            TeacherId = 5,
                            Title = "Desktop Support"
                        },
                        new
                        {
                            ClassId = 12,
                            DayId = 4,
                            MilitaryTime = "1400",
                            Number = 301,
                            TeacherId = 5,
                            Title = "Entity Framework"
                        },
                        new
                        {
                            ClassId = 13,
                            DayId = 4,
                            MilitaryTime = "1600",
                            Number = 301,
                            TeacherId = 5,
                            Title = "NodeJs"
                        },
                        new
                        {
                            ClassId = 14,
                            DayId = 1,
                            MilitaryTime = "1000",
                            Number = 201,
                            TeacherId = 4,
                            Title = "Java Language"
                        });
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DayId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            Name = "Monday"
                        },
                        new
                        {
                            DayId = 2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            DayId = 3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            DayId = 4,
                            Name = "Thursday"
                        },
                        new
                        {
                            DayId = 5,
                            Name = "Friday"
                        },
                        new
                        {
                            DayId = 6,
                            Name = "Saturday"
                        },
                        new
                        {
                            DayId = 7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            FirstName = "Hojjat",
                            LastName = "Hasanpour"
                        },
                        new
                        {
                            TeacherId = 2,
                            FirstName = "Evan",
                            LastName = "Gudmestad"
                        },
                        new
                        {
                            TeacherId = 3,
                            FirstName = "Arthur",
                            LastName = "Morgan"
                        },
                        new
                        {
                            TeacherId = 4,
                            FirstName = "Charles",
                            LastName = "Smith"
                        },
                        new
                        {
                            TeacherId = 5,
                            FirstName = "Hosea",
                            LastName = "Matthews"
                        });
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Class", b =>
                {
                    b.HasOne("RankenClassSchedule.Models.DomainModels.Day", "Day")
                        .WithMany("Classes")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RankenClassSchedule.Models.DomainModels.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Day", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Teacher", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
